This fixes a bug with the current Setup UI on Linux:
java.io.IOException: Cannot run program ""/home/fury/Software/Android-SDK/tools/android": error=2, Datei oder Verzeichnis nicht gefunden
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at java.lang.Runtime.exec(Runtime.java:450)
	at java.lang.Runtime.exec(Runtime.java:347)
	at com.badlogic.gdx.setup.GdxSetupUI.generate(Unknown Source)
	at com.badlogic.gdx.setup.GdxSetupUI$UI$4.actionPerformed(Unknown Source)

The problem comes from manipulating file names directly instead of using the java.io.File API.
I didn't change the Windows branch because I'm not able to test it at the moment.